apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 3
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: counter-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000